import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarItem, 
  MenubarContent,
  MenubarShortcut
} from "@/components/ui/menubar"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className = "fixed top-10 w-screen flex justify-center h-1/10 ">
        <Menubar>
          <MenubarMenu>
              <a href = "harddisk"><MenubarTrigger>Inventory</MenubarTrigger></a>
          </MenubarMenu>
          <MenubarMenu>
              <MenubarTrigger>Add</MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  New Movie <MenubarShortcut>⌘T</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>
                  New Harddisk <MenubarShortcut>⌘N</MenubarShortcut>
                </MenubarItem>
                <MenubarItem>
                  New Rental <MenubarShortcut>⌘N</MenubarShortcut>
                </MenubarItem>
              </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
              <a href = "harddisk"><MenubarTrigger>Return </MenubarTrigger></a>
          </MenubarMenu>
          <MenubarMenu>
              <MenubarTrigger>Home</MenubarTrigger>
          </MenubarMenu>
        </Menubar>
        </div>
        {children}
      </body>
    </html>
  );
}
