import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {
  Menubar,
  MenubarMenu,
  MenubarTrigger,
  MenubarItem
} from "@/components/ui/menubar"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className = "fixed top-10 w-screen flex justify-center h-1/10 ">
          <Menubar>
            <MenubarMenu>
                <a href = "/movies"><MenubarTrigger>Movies</MenubarTrigger></a>
            </MenubarMenu>
            <MenubarMenu>
                <a href = "/harddisk"><MenubarTrigger>Harddisk</MenubarTrigger></a>
            </MenubarMenu>
            <MenubarMenu>
                <a href = "/rentals"><MenubarTrigger>Rentals</MenubarTrigger></a>
            </MenubarMenu>
            <MenubarMenu>
                <a href = "/rentals/modify"><MenubarTrigger>Modify Rental</MenubarTrigger></a>
            </MenubarMenu>
          </Menubar>
          </div>
          {children}
        </body>
      </html>
  );
}
